version: '3.8'
services:
  mapminer:
    build: .
    container_name: mapminer
    ports:
      - "8000:8000"
    volumes:
      - ./outputs:/app/outputs
      - ./gmapsdata:/app/gmapsdata
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
